### ISSUE TITLE
how to use it with tbb?

### ISSUE THREAD

**Issue by JoeisZcx** [dthuerck/mapmap_cpu#11]
hi,
i want to know how can i use it with tbb and where should i add the path of tbb.i tryed many time but appear the same error. 
thank you very much if you can answer me.

**Comment by dthuerck** [comment]
Hi,
after running CMake, type
`ccmake .`

and set, according to README,

- `TBB_INCLUDE_DIRS` path containing the tbb/ folder with include files, e.g. /usr/include
- `TBB_LIBRARY` - path containing the TBB library files, e.g. /lib,

meaning: set TBB_INCLUDE_DIRS to the folder that contains - amongst others - 'tbb.h' and TBB_LIBRARY to the folder containing - amongst others - libtbb.so.
