### ISSUE TITLE
How can I change the weight of unary costs and pairwise costs?

### ISSUE THREAD

**Issue by linmqing** [dthuerck/mapmap_cpu#12]
Sorry, it is my mistake. I Failed to add edge to mapsolver, so the pairwise didn't work.

================================================================
Hi, 

I want to have a more continuous labels' result, so I think I should increase the weight of pairwise costs (smooth term in energy function) to weaken the impact of unary costs (data term in energy function).

However, I tried to change parameter of 'PairwisePotts' or the costs set to unaries, but both them didn't work. 

**Even I set the pairwise to be 0, the results were binary same.**
Does the  pairwise really work?

I wonder how can I adjust the weights.

**Comment by dthuerck** [comment]
Glad you found a solution!

One more hint: when adding edges to the graph, you can include edge weights - these weights are then applied to the pairwise costs. That might come in handy for classes of costs that do not support weights out-of-the-box.

**Comment by linmqing** [comment]
Oh, it's great! Thank you very much.
