### ISSUE TITLE
crashed at runtime when linked to tbb 2018_U5

### ISSUE THREAD

**Issue by GucciPrada** [dthuerck/mapmap_cpu#13]
hi, Daniel
  I'm not sure if this is the right place to open this issue. forgive me if wrong.
  I have tried to compile in xcode 9.4 [mvs-texturing](https://github.com/nmoehrle/mvs-texturing) which depends on master branch of mapmap_cpu  , but mvs-texturing's demo app(namely texrecon) crashed at runtime. The call trace show that it crashes at mapmap's DynamicProgramming Solver, like this:(each time it crashes at  line 99)
![image](https://user-images.githubusercontent.com/13183041/44782947-71b93f80-abbb-11e8-8fe0-fd0bc88e6319.png)
It crashes when  DynamicProgrammingTableEntry<COSTTYPE, SIMDWIDTH>::optimize_entry() is ready to return, releasing the local variable named solver which is an unique_ptr instance.
   The wierd thing is: when i switch to xcode 9.2 and compile and run it, it turns out everything is fine. 
   Do you figure out why did that crash happen?

**Comment by dthuerck** [comment]
Hi,

did you encounter the same problem in other OS's? DUe to lack of access to a mac around here, I'm having a hard time reproducing this bug ;)

**Comment by GucciPrada** [comment]
Hi,
so far I've just tried on MacOS High Serria 10.13.6 and iOS 11.4.1. 

xcode 9.4 is wierd, xcode 9.2 is ok.

I'll try on ubuntu and windows and see if I can reproduce this issue.

**Comment by GucciPrada** [comment]
hi @dthuerck ,
I've tried on Ubuntu 16.0.4+Gcc 5.5.0+[tbb2018_U5](https://github.com/01org/tbb/releases/download/2018_U5/tbb2018_20180618oss_lin.tgz), and as expected, everything is fine.
