### ISSUE TITLE
Variable length array causes issues when compiling with MSVC 

### ISSUE THREAD

**Issue by h00shi** [dthuerck/mapmap_cpu#14]
Hi,

In the file ``mapmap_cpu/mapmap/source/tree_sampler_instances/lock_free_tree_sampler.impl.h`` line ``475`` a variable length array has been defined:
``` luint_t buf[m_buf_edges];```
This is fine when compiling with gcc, but on MSVC it seems to cause compilation errors.

Maybe changing  `` const luint_t m_buf_edges = 4;`` to ``static constexpr luint_t m_buf_edges = 4;``  in ``lock_free_tree_sampler.h`` can help.

Thanks

**Comment by dthuerck** [comment]
Thanks for reporting that! I'll change it from a variable length array to a dynamically allocated one.

**Comment by h00shi** [comment]
I think it should be 
``std::unique_ptr<luint_t> buf =   std::unique_ptr<luint_t>(new luint_t[m_buf_edges]); ``
rather than 
``std::unique_ptr<luint_t[]> buf =   std::unique_ptr<luint_t[]>(new luint_t[m_buf_edges]);``
Otherwise, it would cause the same issue as #9.

**Comment by dthuerck** [comment]
Hi,

you are - again - absolutely right! Thanks, I've just pushed that update.
Sorry for the delay, though.

**Comment by h00shi** [comment]
Thank you for the fix.
