### ISSUE TITLE
bug in prev_level()

### ISSUE THREAD

**Issue by cdcseacave** [dthuerck/mapmap_cpu#21]
there is clearly a bug in `prev_level()` though I am not sure of the right fix (depends if `m_previous` refers to positive or negative previous); I guess the fix should be `m_previous = (m_level ? &m_levels[m_level - 1] : NULL)`, but pls confirm:

https://github.com/dthuerck/mapmap_cpu/blob/master/mapmap/source/multilevel.impl.h#L152

**Comment by dthuerck** [comment]
Hi there,

thanks for reporting this and sorry for my delay, I'm pretty busy ATM. I'm guessing this occurs when using mvs-texturing? If so, is there anyway I can get some (small) input data to replay the problem on my side?

Thanks!

**Comment by dthuerck** [comment]
*push*

Could you provide me with your input data in order to replicate the problem?

**Comment by cdcseacave** [comment]
sry, I gave up trying to make this work, and I removed all the source code related to it
