### ISSUE TITLE
oneTBB removes tbb::task

### ISSUE THREAD

**Issue by bartoszek** [dthuerck/mapmap_cpu#30]
tbb:2020 deprecates and oneTBB removes `tbb::task` `tbb::task_list` and related functions.
The suggested solution is to replace its usage with `tbb::task_group` `tbb::flow::graph`
https://www.intel.com/content/dam/develop/external/us/en/documents/tbbrevamp.pdf

**Comment by dthuerck** [comment]
Hi, thanks for pointing that out. I'll get right on adapting the code!
