### ISSUE TITLE
Setting Pairwise costs table from a std::vector fails

### ISSUE THREAD

**Issue by lukac** [dthuerck/mapmap_cpu#40]
When trying to set pairwise costs table from a `std::vector` as opposed to an array, the call fails. The problem is on this line: https://github.com/dthuerck/mapmap_cpu/blob/master/mapmap/source/cost_instances/pairwise_table.impl.h#L100

With the very last `l_a`, the expression `(li_a + 1) * len_b` indexes beyond the end of the vector, and taking a pointer to that is an illegal operation.

A fix would be either passing iterators instead of pointers to `std::copy` (i.e. `packed_table.begin()+(li_a * len_b)`) or taking the data pointer of the vector and then using pointer arithmetic on that (i.e. `packed_table.data()+(li_a * len_b)`).

**Comment by dthuerck** [comment]
Thanks! COmmit is on its way, should be fixed in a sec.
