### ISSUE TITLE
SSE 4.2 implementation of v_masked_store() contains AVX code

### ISSUE THREAD

**Issue by andre-schulz** [dthuerck/mapmap_cpu#7]
Hi Daniel,

recently an issue was opened in nmoehrle/mvs-texturing/issues/100 where a compile error was reported in mapmap. It turned out that mapmap's SSE 4.2 implementation of [`v_masked_store()`](https://github.com/dthuerck/mapmap_cpu/blob/957914ae2e28abaa5580c5c6e98daae2a97fac5e/mapmap/source/vector_math.impl.h#L1049) includes a call to `_mm_maskstore_ps()` which is an AVX instruction.

Regards,
Andre

**Comment by dthuerck** [comment]
Kudos to @magcks for his PR!
